### ISSUE TITLE
Cannot find stop_words_ja.txt

### ISSUE THREAD

**Issue by daisukelab** [chakki-works/chABSA-dataset#2]
Hi, I wanted to try notebook baseline slot 3, but I have following problems.

- It seems the file stop_words_ja.txt is missing.
- `Path.cwd().parent.joinpath("data/processed")` would be replaced with `chABSA-dataset`. Is this correct?

Anyway thank you for making this dataset open. I'd appreciate if I could have any clue to my issues.

**Comment by icoxfog417** [comment]
Thank you for using chABSA-dataset!

Your reported phenomenon seems to be caused by the Jupyter root folder. Please run `jupyter notebook` on the chABSA-dataset root. [`stop_words_ja.txt` is located on resource folder](https://github.com/chakki-works/chABSA-dataset/tree/master/notebooks/resource).

**Comment by daisukelab** [comment]
Thank you for your comment, and I'm sorry I was not careful enough to find the file.
I could solve the issue, and reproduce the baseline notebook.
Thanks again.
